/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
    DocumentToJSONTyped,
} from './Document';

/**
 * 
 * @export
 * @interface BulkUploadRequest
 */
export interface BulkUploadRequest {
    /**
     * 
     * @type {Array<Document>}
     * @memberof BulkUploadRequest
     */
    documents: Array<Document>;
}

/**
 * Check if a given object implements the BulkUploadRequest interface.
 */
export function instanceOfBulkUploadRequest(value: object): value is BulkUploadRequest {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function BulkUploadRequestFromJSON(json: any): BulkUploadRequest {
    return BulkUploadRequestFromJSONTyped(json, false);
}

export function BulkUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(DocumentFromJSON)),
    };
}

export function BulkUploadRequestToJSON(json: any): BulkUploadRequest {
    return BulkUploadRequestToJSONTyped(json, false);
}

export function BulkUploadRequestToJSONTyped(value?: BulkUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documents': ((value['documents'] as Array<any>).map(DocumentToJSON)),
    };
}

