/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeView } from './NodeView';
import {
    NodeViewFromJSON,
    NodeViewFromJSONTyped,
    NodeViewToJSON,
    NodeViewToJSONTyped,
} from './NodeView';

/**
 * Latest cluster state as persisted by the encoder leader.
 * @export
 * @interface ClusterView
 */
export interface ClusterView {
    /**
     * Map of node ID to node snapshot for all nodes that have reported within the expiry window
     * @type {{ [key: string]: NodeView; }}
     * @memberof ClusterView
     */
    nodes?: { [key: string]: NodeView; };
}

/**
 * Check if a given object implements the ClusterView interface.
 */
export function instanceOfClusterView(value: object): value is ClusterView {
    return true;
}

export function ClusterViewFromJSON(json: any): ClusterView {
    return ClusterViewFromJSONTyped(json, false);
}

export function ClusterViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterView {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': json['nodes'] == null ? undefined : (mapValues(json['nodes'], NodeViewFromJSON)),
    };
}

export function ClusterViewToJSON(json: any): ClusterView {
    return ClusterViewToJSONTyped(json, false);
}

export function ClusterViewToJSONTyped(value?: ClusterView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodes': value['nodes'] == null ? undefined : (mapValues(value['nodes'], NodeViewToJSON)),
    };
}

