/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionExistsResponse
 */
export interface CollectionExistsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CollectionExistsResponse
     */
    _exists: boolean;
}

/**
 * Check if a given object implements the CollectionExistsResponse interface.
 */
export function instanceOfCollectionExistsResponse(value: object): value is CollectionExistsResponse {
    if (!('_exists' in value) || value['_exists'] === undefined) return false;
    return true;
}

export function CollectionExistsResponseFromJSON(json: any): CollectionExistsResponse {
    return CollectionExistsResponseFromJSONTyped(json, false);
}

export function CollectionExistsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionExistsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'],
    };
}

export function CollectionExistsResponseToJSON(json: any): CollectionExistsResponse {
    return CollectionExistsResponseToJSONTyped(json, false);
}

export function CollectionExistsResponseToJSONTyped(value?: CollectionExistsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exists': value['_exists'],
    };
}

