/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueInfo } from './QueueInfo';
import {
    QueueInfoFromJSONTyped,
    QueueInfoToJSONTyped,
} from './QueueInfo';
/**
 * Persisted index statistics for a collection (encoder-maintained counts) and queue counts.
 * @export
 * @interface CollectionStatsResponse
 */
export interface CollectionStatsResponse {
    /**
     * Number of documents reflected in collection stats
     * @type {number}
     * @memberof CollectionStatsResponse
     */
    doc_count: number;
    /**
     * Counts of documents in each queue state
     * @type {QueueInfo}
     * @memberof CollectionStatsResponse
     */
    queue: QueueInfo;
}

/**
 * Check if a given object implements the CollectionStatsResponse interface.
 */
export function instanceOfCollectionStatsResponse(value: object): value is CollectionStatsResponse {
    if (!('doc_count' in value) || value['doc_count'] === undefined) return false;
    if (!('queue' in value) || value['queue'] === undefined) return false;
    return true;
}

export function CollectionStatsResponseFromJSON(json: any): CollectionStatsResponse {
    return CollectionStatsResponseFromJSONTyped(json, false);
}

export function CollectionStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'doc_count': json['doc_count'],
        'queue': QueueInfoFromJSONTyped(json['queue'], false),
    };
}

export function CollectionStatsResponseToJSON(json: any): CollectionStatsResponse {
    return CollectionStatsResponseToJSONTyped(json, false);
}

export function CollectionStatsResponseToJSONTyped(value?: CollectionStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'doc_count': value['doc_count'],
        'queue': QueueInfoToJSONTyped(value['queue'], false),
    };
}

