/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataIndex } from './MetadataIndex';
import {
    MetadataIndexFromJSON,
    MetadataIndexFromJSONTyped,
    MetadataIndexToJSON,
    MetadataIndexToJSONTyped,
} from './MetadataIndex';
import type { VectorConfig } from './VectorConfig';
import {
    VectorConfigFromJSON,
    VectorConfigFromJSONTyped,
    VectorConfigToJSON,
    VectorConfigToJSONTyped,
} from './VectorConfig';

/**
 * API model for collection configuration - uses VectorConfig.
 * @export
 * @interface CollectionConfig
 */
export interface CollectionConfig {
    /**
     * List of vector configurations for this collection
     * @type {Array<VectorConfig>}
     * @memberof CollectionConfig
     */
    vectors: Array<VectorConfig>;
    /**
     * Whether to store document content in the database.
     * @type {boolean}
     * @memberof CollectionConfig
     */
    store_content?: boolean;
    /**
     * List of metadata fields to index for filtering and sorting
     * @type {Array<MetadataIndex>}
     * @memberof CollectionConfig
     */
    metadata_indexes?: Array<MetadataIndex>;
}

/**
 * Check if a given object implements the CollectionConfig interface.
 */
export function instanceOfCollectionConfig(value: object): value is CollectionConfig {
    if (!('vectors' in value) || value['vectors'] === undefined) return false;
    return true;
}

export function CollectionConfigFromJSON(json: any): CollectionConfig {
    return CollectionConfigFromJSONTyped(json, false);
}

export function CollectionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'vectors': ((json['vectors'] as Array<any>).map(VectorConfigFromJSON)),
        'store_content': json['store_content'] == null ? undefined : json['store_content'],
        'metadata_indexes': json['metadata_indexes'] == null ? undefined : ((json['metadata_indexes'] as Array<any>).map(MetadataIndexFromJSON)),
    };
}

export function CollectionConfigToJSON(json: any): CollectionConfig {
    return CollectionConfigToJSONTyped(json, false);
}

export function CollectionConfigToJSONTyped(value?: CollectionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vectors': ((value['vectors'] as Array<any>).map(VectorConfigToJSON)),
        'store_content': value['store_content'],
        'metadata_indexes': value['metadata_indexes'] == null ? undefined : ((value['metadata_indexes'] as Array<any>).map(MetadataIndexToJSON)),
    };
}

