/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Vector } from './Vector';
import {
    VectorFromJSON,
    VectorFromJSONTyped,
    VectorToJSON,
    VectorToJSONTyped,
} from './Vector';

/**
 * Custom vector for documents - adds field specification
 * @export
 * @interface CustomDocumentVector
 */
export interface CustomDocumentVector {
    /**
     * Name of the vector (must match collection config)
     * @type {string}
     * @memberof CustomDocumentVector
     */
    vector_name: string;
    /**
     * 
     * @type {Vector}
     * @memberof CustomDocumentVector
     */
    vector: Vector;
    /**
     * Document field this vector is for (name, description, or content)
     * @type {CustomDocumentVectorFieldEnum}
     * @memberof CustomDocumentVector
     */
    field: CustomDocumentVectorFieldEnum;
}


/**
 * @export
 */
export const CustomDocumentVectorFieldEnum = {
    Name: 'name',
    Description: 'description',
    Content: 'content'
} as const;
export type CustomDocumentVectorFieldEnum = typeof CustomDocumentVectorFieldEnum[keyof typeof CustomDocumentVectorFieldEnum];


/**
 * Check if a given object implements the CustomDocumentVector interface.
 */
export function instanceOfCustomDocumentVector(value: object): value is CustomDocumentVector {
    if (!('vector_name' in value) || value['vector_name'] === undefined) return false;
    if (!('vector' in value) || value['vector'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    return true;
}

export function CustomDocumentVectorFromJSON(json: any): CustomDocumentVector {
    return CustomDocumentVectorFromJSONTyped(json, false);
}

export function CustomDocumentVectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDocumentVector {
    if (json == null) {
        return json;
    }
    return {
        
        'vector_name': json['vector_name'],
        'vector': VectorFromJSON(json['vector']),
        'field': json['field'],
    };
}

export function CustomDocumentVectorToJSON(json: any): CustomDocumentVector {
    return CustomDocumentVectorToJSONTyped(json, false);
}

export function CustomDocumentVectorToJSONTyped(value?: CustomDocumentVector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vector_name': value['vector_name'],
        'vector': VectorToJSON(value['vector']),
        'field': value['field'],
    };
}

