/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Vector } from './Vector';
import {
    VectorFromJSON,
    VectorFromJSONTyped,
    VectorToJSON,
    VectorToJSONTyped,
} from './Vector';

/**
 * Base custom vector model for search queries
 * @export
 * @interface CustomVector
 */
export interface CustomVector {
    /**
     * Name of the vector (must match collection config)
     * @type {string}
     * @memberof CustomVector
     */
    vector_name: string;
    /**
     * 
     * @type {Vector}
     * @memberof CustomVector
     */
    vector: Vector;
}

/**
 * Check if a given object implements the CustomVector interface.
 */
export function instanceOfCustomVector(value: object): value is CustomVector {
    if (!('vector_name' in value) || value['vector_name'] === undefined) return false;
    if (!('vector' in value) || value['vector'] === undefined) return false;
    return true;
}

export function CustomVectorFromJSON(json: any): CustomVector {
    return CustomVectorFromJSONTyped(json, false);
}

export function CustomVectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomVector {
    if (json == null) {
        return json;
    }
    return {
        
        'vector_name': json['vector_name'],
        'vector': VectorFromJSON(json['vector']),
    };
}

export function CustomVectorToJSON(json: any): CustomVector {
    return CustomVectorToJSONTyped(json, false);
}

export function CustomVectorToJSONTyped(value?: CustomVector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vector_name': value['vector_name'],
        'vector': VectorToJSON(value['vector']),
    };
}

