/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentStatus } from './DocumentStatus';
import {
    DocumentStatusFromJSON,
    DocumentStatusFromJSONTyped,
    DocumentStatusToJSON,
    DocumentStatusToJSONTyped,
} from './DocumentStatus';

/**
 * Complete status response for a document including queue states.
 * @export
 * @interface DocumentStatusResponse
 */
export interface DocumentStatusResponse {
    /**
     * List of statuses sorted by timestamp (newest first)
     * @type {Array<DocumentStatus>}
     * @memberof DocumentStatusResponse
     */
    statuses: Array<DocumentStatus>;
}

/**
 * Check if a given object implements the DocumentStatusResponse interface.
 */
export function instanceOfDocumentStatusResponse(value: object): value is DocumentStatusResponse {
    if (!('statuses' in value) || value['statuses'] === undefined) return false;
    return true;
}

export function DocumentStatusResponseFromJSON(json: any): DocumentStatusResponse {
    return DocumentStatusResponseFromJSONTyped(json, false);
}

export function DocumentStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statuses': ((json['statuses'] as Array<any>).map(DocumentStatusFromJSON)),
    };
}

export function DocumentStatusResponseToJSON(json: any): DocumentStatusResponse {
    return DocumentStatusResponseToJSONTyped(json, false);
}

export function DocumentStatusResponseToJSONTyped(value?: DocumentStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statuses': ((value['statuses'] as Array<any>).map(DocumentStatusToJSON)),
    };
}

