/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata field index configuration
 * @export
 * @interface MetadataIndex
 */
export interface MetadataIndex {
    /**
     * Metadata field key to index
     * @type {string}
     * @memberof MetadataIndex
     */
    key: string;
    /**
     * Type of the metadata value
     * @type {MetadataIndexTypeEnum}
     * @memberof MetadataIndex
     */
    type: MetadataIndexTypeEnum;
}


/**
 * @export
 */
export const MetadataIndexTypeEnum = {
    String: 'string',
    Integer: 'integer',
    Float: 'float',
    Boolean: 'boolean',
    Datetime: 'datetime'
} as const;
export type MetadataIndexTypeEnum = typeof MetadataIndexTypeEnum[keyof typeof MetadataIndexTypeEnum];


/**
 * Check if a given object implements the MetadataIndex interface.
 */
export function instanceOfMetadataIndex(value: object): value is MetadataIndex {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MetadataIndexFromJSON(json: any): MetadataIndex {
    return MetadataIndexFromJSONTyped(json, false);
}

export function MetadataIndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataIndex {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'type': json['type'],
    };
}

export function MetadataIndexToJSON(json: any): MetadataIndex {
    return MetadataIndexToJSONTyped(json, false);
}

export function MetadataIndexToJSONTyped(value?: MetadataIndex | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'type': value['type'],
    };
}

