/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Recursive metadata filter structure (modeled on Qdrant filter with and/or/not).
 * @export
 * @interface MetadataFilter
 */
export interface MetadataFilter {
    /**
     * All conditions in this list must match (AND)
     * @type {Array<MetadataFilter>}
     * @memberof MetadataFilter
     */
    and?: Array<MetadataFilter>;
    /**
     * Any condition in this list must match (OR)
     * @type {Array<MetadataFilter>}
     * @memberof MetadataFilter
     */
    or?: Array<MetadataFilter>;
    /**
     * This condition must NOT match (NOT)
     * @type {MetadataFilter}
     * @memberof MetadataFilter
     */
    not?: MetadataFilter;
    /**
     * Metadata field key (for field condition)
     * @type {string}
     * @memberof MetadataFilter
     */
    key?: string;
    /**
     * Comparison operator
     * @type {MetadataFilterOpEnum}
     * @memberof MetadataFilter
     */
    op?: MetadataFilterOpEnum;
    /**
     * 
     * @type {any}
     * @memberof MetadataFilter
     */
    value?: any | null;
}


/**
 * @export
 */
export const MetadataFilterOpEnum = {
    Eq: 'eq',
    Lt: 'lt',
    Gt: 'gt',
    Lte: 'lte',
    Gte: 'gte'
} as const;
export type MetadataFilterOpEnum = typeof MetadataFilterOpEnum[keyof typeof MetadataFilterOpEnum];


/**
 * Check if a given object implements the MetadataFilter interface.
 */
export function instanceOfMetadataFilter(value: object): value is MetadataFilter {
    return true;
}

export function MetadataFilterFromJSON(json: any): MetadataFilter {
    return MetadataFilterFromJSONTyped(json, false);
}

export function MetadataFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'and': json['and'] == null ? undefined : ((json['and'] as Array<any>).map(MetadataFilterFromJSON)),
        'or': json['or'] == null ? undefined : ((json['or'] as Array<any>).map(MetadataFilterFromJSON)),
        'not': json['not'] == null ? undefined : MetadataFilterFromJSON(json['not']),
        'key': json['key'] == null ? undefined : json['key'],
        'op': json['op'] == null ? undefined : json['op'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetadataFilterToJSON(json: any): MetadataFilter {
    return MetadataFilterToJSONTyped(json, false);
}

export function MetadataFilterToJSONTyped(value?: MetadataFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'and': value['and'] == null ? undefined : ((value['and'] as Array<any>).map(MetadataFilterToJSON)),
        'or': value['or'] == null ? undefined : ((value['or'] as Array<any>).map(MetadataFilterToJSON)),
        'not': MetadataFilterToJSON(value['not']),
        'key': value['key'],
        'op': value['op'],
        'value': value['value'],
    };
}

