/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeView } from './NodeView';
import {
    NodeViewFromJSON,
    NodeViewFromJSONTyped,
    NodeViewToJSON,
    NodeViewToJSONTyped,
} from './NodeView';

/**
 * Latest metrics state as persisted by the encoder leader.
 * @export
 * @interface Metrics
 */
export interface Metrics {
    /**
     * Map of node ID to node snapshot for all nodes that have reported within the expiry window
     * @type {{ [key: string]: NodeView; }}
     * @memberof Metrics
     */
    nodes?: { [key: string]: NodeView; };
}

/**
 * Check if a given object implements the Metrics interface.
 */
export function instanceOfMetrics(value: object): value is Metrics {
    return true;
}

export function MetricsFromJSON(json: any): Metrics {
    return MetricsFromJSONTyped(json, false);
}

export function MetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metrics {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': json['nodes'] == null ? undefined : (mapValues(json['nodes'], NodeViewFromJSON)),
    };
}

export function MetricsToJSON(json: any): Metrics {
    return MetricsToJSONTyped(json, false);
}

export function MetricsToJSONTyped(value?: Metrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodes': value['nodes'] == null ? undefined : (mapValues(value['nodes'], NodeViewToJSON)),
    };
}

