/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetricsBucket } from './MetricsBucket';
import {
    MetricsBucketFromJSON,
    MetricsBucketFromJSONTyped,
    MetricsBucketToJSON,
    MetricsBucketToJSONTyped,
} from './MetricsBucket';

/**
 * Historical buckets for a single metric key at a given resolution.
 * @export
 * @interface MetricTrend
 */
export interface MetricTrend {
    /**
     * Metric key
     * @type {string}
     * @memberof MetricTrend
     */
    key: string;
    /**
     * Bucket resolution in seconds
     * @type {number}
     * @memberof MetricTrend
     */
    bucket_seconds: number;
    /**
     * Buckets ordered by bucket_start ascending
     * @type {Array<MetricsBucket>}
     * @memberof MetricTrend
     */
    buckets?: Array<MetricsBucket>;
}

/**
 * Check if a given object implements the MetricTrend interface.
 */
export function instanceOfMetricTrend(value: object): value is MetricTrend {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('bucket_seconds' in value) || value['bucket_seconds'] === undefined) return false;
    return true;
}

export function MetricTrendFromJSON(json: any): MetricTrend {
    return MetricTrendFromJSONTyped(json, false);
}

export function MetricTrendFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricTrend {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'bucket_seconds': json['bucket_seconds'],
        'buckets': json['buckets'] == null ? undefined : ((json['buckets'] as Array<any>).map(MetricsBucketFromJSON)),
    };
}

export function MetricTrendToJSON(json: any): MetricTrend {
    return MetricTrendToJSONTyped(json, false);
}

export function MetricTrendToJSONTyped(value?: MetricTrend | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'bucket_seconds': value['bucket_seconds'],
        'buckets': value['buckets'] == null ? undefined : ((value['buckets'] as Array<any>).map(MetricsBucketToJSON)),
    };
}

