/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricDefinitionItem
 */
export interface MetricDefinitionItem {
    /**
     * Stable metric identifier
     * @type {string}
     * @memberof MetricDefinitionItem
     */
    key: string;
    /**
     * Unit label (e.g. req, ms, batch)
     * @type {string}
     * @memberof MetricDefinitionItem
     */
    unit: string;
    /**
     * Description of this metric
     * @type {string}
     * @memberof MetricDefinitionItem
     */
    description: string;
}

/**
 * Check if a given object implements the MetricDefinitionItem interface.
 */
export function instanceOfMetricDefinitionItem(value: object): value is MetricDefinitionItem {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function MetricDefinitionItemFromJSON(json: any): MetricDefinitionItem {
    return MetricDefinitionItemFromJSONTyped(json, false);
}

export function MetricDefinitionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricDefinitionItem {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'unit': json['unit'],
        'description': json['description'],
    };
}

export function MetricDefinitionItemToJSON(json: any): MetricDefinitionItem {
    return MetricDefinitionItemToJSONTyped(json, false);
}

export function MetricDefinitionItemToJSONTyped(value?: MetricDefinitionItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'unit': value['unit'],
        'description': value['description'],
    };
}

