/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One mergeable aligned bucket that can be used for live and historical metrics.
 * @export
 * @interface MetricsBucket
 */
export interface MetricsBucket {
    /**
     * Metric name for this bucket
     * @type {string}
     * @memberof MetricsBucket
     */
    key: string;
    /**
     * Optional metric dimensions for this bucket
     * @type {Array<string>}
     * @memberof MetricsBucket
     */
    dims?: Array<string>;
    /**
     * Unix timestamp of the inclusive bucket start boundary
     * @type {number}
     * @memberof MetricsBucket
     */
    bucket_start: number;
    /**
     * Bucket duration in seconds
     * @type {number}
     * @memberof MetricsBucket
     */
    bucket_seconds: number;
    /**
     * Mergeable numerator for the bucket
     * @type {number}
     * @memberof MetricsBucket
     */
    value: number;
    /**
     * Mergeable denominator for average-like metrics
     * @type {number}
     * @memberof MetricsBucket
     */
    n?: number;
}

/**
 * Check if a given object implements the MetricsBucket interface.
 */
export function instanceOfMetricsBucket(value: object): value is MetricsBucket {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('bucket_start' in value) || value['bucket_start'] === undefined) return false;
    if (!('bucket_seconds' in value) || value['bucket_seconds'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MetricsBucketFromJSON(json: any): MetricsBucket {
    return MetricsBucketFromJSONTyped(json, false);
}

export function MetricsBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'dims': json['dims'] == null ? undefined : json['dims'],
        'bucket_start': json['bucket_start'],
        'bucket_seconds': json['bucket_seconds'],
        'value': json['value'],
        'n': json['n'] == null ? undefined : json['n'],
    };
}

export function MetricsBucketToJSON(json: any): MetricsBucket {
    return MetricsBucketToJSONTyped(json, false);
}

export function MetricsBucketToJSONTyped(value?: MetricsBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'dims': value['dims'],
        'bucket_start': value['bucket_start'],
        'bucket_seconds': value['bucket_seconds'],
        'value': value['value'],
        'n': value['n'],
    };
}

