/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WindowSample } from './WindowSample';
import {
    WindowSampleFromJSON,
    WindowSampleFromJSONTyped,
    WindowSampleToJSON,
    WindowSampleToJSONTyped,
} from './WindowSample';

/**
 * One metric stream on a node with rolling-window snapshots.
 * 
 * key[0] is the metric name (e.g. 'batches', 'inference_ms', 'inference_origin_ms', 'hops').
 * key[1:] are optional dimensions (e.g. vector type, model name, revision).
 * windows are keyed by window size in seconds.
 * @export
 * @interface NodeMetricSeries
 */
export interface NodeMetricSeries {
    /**
     * Compound key: [metric_name, *dimensions]
     * @type {Array<string>}
     * @memberof NodeMetricSeries
     */
    key: Array<string>;
    /**
     * Rolling-window snapshots keyed by window size in seconds
     * @type {{ [key: string]: WindowSample; }}
     * @memberof NodeMetricSeries
     */
    windows?: { [key: string]: WindowSample; };
    /**
     * UTC timestamp (time.time()) of the most recent sample for this series
     * @type {number}
     * @memberof NodeMetricSeries
     */
    last_seen?: number;
}

/**
 * Check if a given object implements the NodeMetricSeries interface.
 */
export function instanceOfNodeMetricSeries(value: object): value is NodeMetricSeries {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function NodeMetricSeriesFromJSON(json: any): NodeMetricSeries {
    return NodeMetricSeriesFromJSONTyped(json, false);
}

export function NodeMetricSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeMetricSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'windows': json['windows'] == null ? undefined : (mapValues(json['windows'], WindowSampleFromJSON)),
        'last_seen': json['last_seen'] == null ? undefined : json['last_seen'],
    };
}

export function NodeMetricSeriesToJSON(json: any): NodeMetricSeries {
    return NodeMetricSeriesToJSONTyped(json, false);
}

export function NodeMetricSeriesToJSONTyped(value?: NodeMetricSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'windows': value['windows'] == null ? undefined : (mapValues(value['windows'], WindowSampleToJSON)),
        'last_seen': value['last_seen'],
    };
}

