/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeMetricSeries } from './NodeMetricSeries';
import {
    NodeMetricSeriesFromJSON,
    NodeMetricSeriesFromJSONTyped,
    NodeMetricSeriesToJSON,
    NodeMetricSeriesToJSONTyped,
} from './NodeMetricSeries';

/**
 * Snapshot of a single cluster node as last reported to the leader.
 * @export
 * @interface NodeView
 */
export interface NodeView {
    /**
     * Node role: 'index', 'query', 'all' for encoder nodes; 'api' for API nodes
     * @type {string}
     * @memberof NodeView
     */
    role: string;
    /**
     * Whether this node is the current encoder leader
     * @type {boolean}
     * @memberof NodeView
     */
    is_leader?: boolean;
    /**
     * Unix timestamp of the last heartbeat received from this node
     * @type {number}
     * @memberof NodeView
     */
    last_seen: number;
    /**
     * Forward-compatible node metadata bag (for load/capacity/gpu/memory/model details and future node status values)
     * @type {{ [key: string]: any; }}
     * @memberof NodeView
     */
    meta?: { [key: string]: any; };
    /**
     * Metric series for this node; empty for API nodes
     * @type {Array<NodeMetricSeries>}
     * @memberof NodeView
     */
    metrics?: Array<NodeMetricSeries>;
}

/**
 * Check if a given object implements the NodeView interface.
 */
export function instanceOfNodeView(value: object): value is NodeView {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('last_seen' in value) || value['last_seen'] === undefined) return false;
    return true;
}

export function NodeViewFromJSON(json: any): NodeView {
    return NodeViewFromJSONTyped(json, false);
}

export function NodeViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeView {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'is_leader': json['is_leader'] == null ? undefined : json['is_leader'],
        'last_seen': json['last_seen'],
        'meta': json['meta'] == null ? undefined : json['meta'],
        'metrics': json['metrics'] == null ? undefined : ((json['metrics'] as Array<any>).map(NodeMetricSeriesFromJSON)),
    };
}

export function NodeViewToJSON(json: any): NodeView {
    return NodeViewToJSONTyped(json, false);
}

export function NodeViewToJSONTyped(value?: NodeView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'is_leader': value['is_leader'],
        'last_seen': value['last_seen'],
        'meta': value['meta'],
        'metrics': value['metrics'] == null ? undefined : ((value['metrics'] as Array<any>).map(NodeMetricSeriesToJSON)),
    };
}

