/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Queue statistics for a collection.
 * Provides counts of documents in different queue states.
 * @export
 * @interface QueueInfo
 */
export interface QueueInfo {
    /**
     * Number of upsert queue entries queued for processing
     * @type {number}
     * @memberof QueueInfo
     */
    queued_upsert: number;
    /**
     * Number of delete queue entries queued for processing
     * @type {number}
     * @memberof QueueInfo
     */
    queued_delete: number;
    /**
     * Number of upsert queue entries requeued after failure
     * @type {number}
     * @memberof QueueInfo
     */
    requeued_upsert: number;
    /**
     * Number of delete queue entries requeued after failure
     * @type {number}
     * @memberof QueueInfo
     */
    requeued_delete: number;
    /**
     * Number of failed upsert queue entries
     * @type {number}
     * @memberof QueueInfo
     */
    failed_upsert: number;
    /**
     * Number of failed delete queue entries
     * @type {number}
     * @memberof QueueInfo
     */
    failed_delete: number;
    /**
     * Total number of queue entries
     * @type {number}
     * @memberof QueueInfo
     */
    total: number;
}

/**
 * Check if a given object implements the QueueInfo interface.
 */
export function instanceOfQueueInfo(value: object): value is QueueInfo {
    if (!('queued_upsert' in value) || value['queued_upsert'] === undefined) return false;
    if (!('queued_delete' in value) || value['queued_delete'] === undefined) return false;
    if (!('requeued_upsert' in value) || value['requeued_upsert'] === undefined) return false;
    if (!('requeued_delete' in value) || value['requeued_delete'] === undefined) return false;
    if (!('failed_upsert' in value) || value['failed_upsert'] === undefined) return false;
    if (!('failed_delete' in value) || value['failed_delete'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function QueueInfoFromJSON(json: any): QueueInfo {
    return QueueInfoFromJSONTyped(json, false);
}

export function QueueInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'queued_upsert': json['queued_upsert'],
        'queued_delete': json['queued_delete'],
        'requeued_upsert': json['requeued_upsert'],
        'requeued_delete': json['requeued_delete'],
        'failed_upsert': json['failed_upsert'],
        'failed_delete': json['failed_delete'],
        'total': json['total'],
    };
}

export function QueueInfoToJSON(json: any): QueueInfo {
    return QueueInfoToJSONTyped(json, false);
}

export function QueueInfoToJSONTyped(value?: QueueInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queued_upsert': value['queued_upsert'],
        'queued_delete': value['queued_delete'],
        'requeued_upsert': value['requeued_upsert'],
        'requeued_delete': value['requeued_delete'],
        'failed_upsert': value['failed_upsert'],
        'failed_delete': value['failed_delete'],
        'total': value['total'],
    };
}

