/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Queue statistics for a collection.
 * Provides counts of documents in different queue states.
 * @export
 * @interface QueueInfo
 */
export interface QueueInfo {
    /**
     * Number of documents queued for processing
     * @type {number}
     * @memberof QueueInfo
     */
    queued: number;
    /**
     * Number of documents requeued after failure
     * @type {number}
     * @memberof QueueInfo
     */
    requeued: number;
    /**
     * Number of failed documents
     * @type {number}
     * @memberof QueueInfo
     */
    failed: number;
    /**
     * Total number of queue entries
     * @type {number}
     * @memberof QueueInfo
     */
    total: number;
}

/**
 * Check if a given object implements the QueueInfo interface.
 */
export function instanceOfQueueInfo(value: object): value is QueueInfo {
    if (!('queued' in value) || value['queued'] === undefined) return false;
    if (!('requeued' in value) || value['requeued'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function QueueInfoFromJSON(json: any): QueueInfo {
    return QueueInfoFromJSONTyped(json, false);
}

export function QueueInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'queued': json['queued'],
        'requeued': json['requeued'],
        'failed': json['failed'],
        'total': json['total'],
    };
}

export function QueueInfoToJSON(json: any): QueueInfo {
    return QueueInfoToJSONTyped(json, false);
}

export function QueueInfoToJSONTyped(value?: QueueInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queued': value['queued'],
        'requeued': value['requeued'],
        'failed': value['failed'],
        'total': value['total'],
    };
}

