/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadyResponse
 */
export interface ReadyResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ReadyResponse
     */
    database: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReadyResponse
     */
    rabbitmq: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReadyResponse
     */
    index: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReadyResponse
     */
    query: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReadyResponse
     */
    ready: boolean;
}

/**
 * Check if a given object implements the ReadyResponse interface.
 */
export function instanceOfReadyResponse(value: object): value is ReadyResponse {
    if (!('database' in value) || value['database'] === undefined) return false;
    if (!('rabbitmq' in value) || value['rabbitmq'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('ready' in value) || value['ready'] === undefined) return false;
    return true;
}

export function ReadyResponseFromJSON(json: any): ReadyResponse {
    return ReadyResponseFromJSONTyped(json, false);
}

export function ReadyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'database': json['database'],
        'rabbitmq': json['rabbitmq'],
        'index': json['index'],
        'query': json['query'],
        'ready': json['ready'],
    };
}

export function ReadyResponseToJSON(json: any): ReadyResponse {
    return ReadyResponseToJSONTyped(json, false);
}

export function ReadyResponseToJSONTyped(value?: ReadyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'database': value['database'],
        'rabbitmq': value['rabbitmq'],
        'index': value['index'],
        'query': value['query'],
        'ready': value['ready'],
    };
}

