/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VectorSearchWeight } from './VectorSearchWeight';
import {
    VectorSearchWeightFromJSON,
    VectorSearchWeightFromJSONTyped,
    VectorSearchWeightToJSON,
    VectorSearchWeightToJSONTyped,
} from './VectorSearchWeight';
import type { CustomVector } from './CustomVector';
import {
    CustomVectorFromJSON,
    CustomVectorFromJSONTyped,
    CustomVectorToJSON,
    CustomVectorToJSONTyped,
} from './CustomVector';
import type { MetadataFilter } from './MetadataFilter';
import {
    MetadataFilterFromJSON,
    MetadataFilterFromJSONTyped,
    MetadataFilterToJSON,
    MetadataFilterToJSONTyped,
} from './MetadataFilter';

/**
 * Configuration for a search query.
 * Defines the query string and vector weights.
 * This is the model that will be sent by end users to the search API endpoint.
 * @export
 * @interface SearchQuery
 */
export interface SearchQuery {
    /**
     * The search query string (max 10000 characters)
     * @type {string}
     * @memberof SearchQuery
     */
    query: string;
    /**
     * List of vectors, fields, and weights to use for searching. If empty, equal weights will be auto-generated for all available vectors.
     * @type {Array<VectorSearchWeight>}
     * @memberof SearchQuery
     */
    vector_weights?: Array<VectorSearchWeight>;
    /**
     * Pre-generated custom vectors for this search query (optional)
     * @type {Array<CustomVector>}
     * @memberof SearchQuery
     */
    custom_vectors?: Array<CustomVector>;
    /**
     * Maximum number of results to return (1 to 100)
     * @type {number}
     * @memberof SearchQuery
     */
    limit?: number;
    /**
     * Optional minimum score threshold. Results below this score will be excluded
     * @type {number}
     * @memberof SearchQuery
     */
    score_threshold?: number;
    /**
     * Optional filter to include only documents with specific tags (max 50 tags, each max 100 characters; cannot contain pipe characters)
     * @type {Array<string>}
     * @memberof SearchQuery
     */
    document_tags?: Array<string>;
    /**
     * If True, documents must have ALL specified tags (AND). If False, documents must have ANY of the specified tags (OR).
     * @type {boolean}
     * @memberof SearchQuery
     */
    document_tags_match_all?: boolean;
    /**
     * Optional recursive metadata filter. Only fields declared in collection metadata_indexes can be filtered.
     * @type {MetadataFilter}
     * @memberof SearchQuery
     */
    metadata_filter?: MetadataFilter;
    /**
     * Whether to include individual vector scores in results
     * @type {boolean}
     * @memberof SearchQuery
     */
    raw_scores?: boolean;
    /**
     * WMTR trigram channel multiplier for this search query.
     * @type {number}
     * @memberof SearchQuery
     */
    wmtr_trigram_weight?: number;
    /**
     * How to combine multi-vector search results. 'rrf' = reciprocal rank fusion (rank-based). 'linear' = min-max normalize each retriever's scores on its prefetch list, then sum weight * normalized score.
     * @type {SearchQueryFusionModeEnum}
     * @memberof SearchQuery
     */
    fusion_mode?: SearchQueryFusionModeEnum;
}


/**
 * @export
 */
export const SearchQueryFusionModeEnum = {
    Rrf: 'rrf',
    Linear: 'linear'
} as const;
export type SearchQueryFusionModeEnum = typeof SearchQueryFusionModeEnum[keyof typeof SearchQueryFusionModeEnum];


/**
 * Check if a given object implements the SearchQuery interface.
 */
export function instanceOfSearchQuery(value: object): value is SearchQuery {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function SearchQueryFromJSON(json: any): SearchQuery {
    return SearchQueryFromJSONTyped(json, false);
}

export function SearchQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'vector_weights': json['vector_weights'] == null ? undefined : ((json['vector_weights'] as Array<any>).map(VectorSearchWeightFromJSON)),
        'custom_vectors': json['custom_vectors'] == null ? undefined : ((json['custom_vectors'] as Array<any>).map(CustomVectorFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'score_threshold': json['score_threshold'] == null ? undefined : json['score_threshold'],
        'document_tags': json['document_tags'] == null ? undefined : json['document_tags'],
        'document_tags_match_all': json['document_tags_match_all'] == null ? undefined : json['document_tags_match_all'],
        'metadata_filter': json['metadata_filter'] == null ? undefined : MetadataFilterFromJSON(json['metadata_filter']),
        'raw_scores': json['raw_scores'] == null ? undefined : json['raw_scores'],
        'wmtr_trigram_weight': json['wmtr_trigram_weight'] == null ? undefined : json['wmtr_trigram_weight'],
        'fusion_mode': json['fusion_mode'] == null ? undefined : json['fusion_mode'],
    };
}

export function SearchQueryToJSON(json: any): SearchQuery {
    return SearchQueryToJSONTyped(json, false);
}

export function SearchQueryToJSONTyped(value?: SearchQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'vector_weights': value['vector_weights'] == null ? undefined : ((value['vector_weights'] as Array<any>).map(VectorSearchWeightToJSON)),
        'custom_vectors': value['custom_vectors'] == null ? undefined : ((value['custom_vectors'] as Array<any>).map(CustomVectorToJSON)),
        'limit': value['limit'],
        'score_threshold': value['score_threshold'],
        'document_tags': value['document_tags'],
        'document_tags_match_all': value['document_tags_match_all'],
        'metadata_filter': MetadataFilterToJSON(value['metadata_filter']),
        'raw_scores': value['raw_scores'],
        'wmtr_trigram_weight': value['wmtr_trigram_weight'],
        'fusion_mode': value['fusion_mode'],
    };
}

