/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemInfoResponse
 */
export interface SystemInfoResponse {
    /**
     * API / deployment version string
     * @type {string}
     * @memberof SystemInfoResponse
     */
    amgix_version: string;
    /**
     * Database product derived from configured URL scheme (no connection string)
     * @type {string}
     * @memberof SystemInfoResponse
     */
    database_kind: string;
    /**
     * Version reported by the database backend after probe
     * @type {string}
     * @memberof SystemInfoResponse
     */
    database_version: string;
    /**
     * Feature flags detected at probe time (e.g. dense vector support)
     * @type {{ [key: string]: boolean; }}
     * @memberof SystemInfoResponse
     */
    database_features: { [key: string]: boolean; };
    /**
     * AMQP broker version from Connection.Start server_properties (e.g. RabbitMQ)
     * @type {string}
     * @memberof SystemInfoResponse
     */
    rabbitmq_version: string;
    /**
     * Number of user collections
     * @type {number}
     * @memberof SystemInfoResponse
     */
    collection_count: number;
}

/**
 * Check if a given object implements the SystemInfoResponse interface.
 */
export function instanceOfSystemInfoResponse(value: object): value is SystemInfoResponse {
    if (!('amgix_version' in value) || value['amgix_version'] === undefined) return false;
    if (!('database_kind' in value) || value['database_kind'] === undefined) return false;
    if (!('database_version' in value) || value['database_version'] === undefined) return false;
    if (!('database_features' in value) || value['database_features'] === undefined) return false;
    if (!('rabbitmq_version' in value) || value['rabbitmq_version'] === undefined) return false;
    if (!('collection_count' in value) || value['collection_count'] === undefined) return false;
    return true;
}

export function SystemInfoResponseFromJSON(json: any): SystemInfoResponse {
    return SystemInfoResponseFromJSONTyped(json, false);
}

export function SystemInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amgix_version': json['amgix_version'],
        'database_kind': json['database_kind'],
        'database_version': json['database_version'],
        'database_features': json['database_features'],
        'rabbitmq_version': json['rabbitmq_version'],
        'collection_count': json['collection_count'],
    };
}

export function SystemInfoResponseToJSON(json: any): SystemInfoResponse {
    return SystemInfoResponseToJSONTyped(json, false);
}

export function SystemInfoResponseToJSONTyped(value?: SystemInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amgix_version': value['amgix_version'],
        'database_kind': value['database_kind'],
        'database_version': value['database_version'],
        'database_features': value['database_features'],
        'rabbitmq_version': value['rabbitmq_version'],
        'collection_count': value['collection_count'],
    };
}

