/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: v1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorLocItem
 */
export interface ValidationErrorLocItem {
}

/**
 * Check if a given object implements the ValidationErrorLocItem interface.
 */
export function instanceOfValidationErrorLocItem(value: object): value is ValidationErrorLocItem {
    return true;
}

export function ValidationErrorLocItemFromJSON(json: any): ValidationErrorLocItem {
    return ValidationErrorLocItemFromJSONTyped(json, false);
}

export function ValidationErrorLocItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorLocItem {
    return json;
}

export function ValidationErrorLocItemToJSON(json: any): ValidationErrorLocItem {
    return ValidationErrorLocItemToJSONTyped(json, false);
}

export function ValidationErrorLocItemToJSONTyped(value?: ValidationErrorLocItem | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

