/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration for a vector generation method.
 * 
 * This model defines how vectors should be generated for a specific field or set of fields.
 * Different vector types have different requirements and behaviors.
 * @export
 * @interface VectorConfig
 */
export interface VectorConfig {
    /**
     * Unique name for this vector configuration
     * @type {string}
     * @memberof VectorConfig
     */
    name: string;
    /**
     * Type of vector (dense_model, sparse_model, full_text, trigrams, whitespace, wmtr, dense_custom, sparse_custom)
     * @type {VectorConfigTypeEnum}
     * @memberof VectorConfig
     */
    type: VectorConfigTypeEnum;
    /**
     * Model name for transformer-based vectors (max 210 characters, e.g., 'sentence-transformers/all-MiniLM-L6-v2'). Used for document indexing.
     * @type {string}
     * @memberof VectorConfig
     */
    model?: string;
    /**
     * Optional model revision (max 210 characters, branch/tag/commit) for specific model version. Used for document indexing.
     * @type {string}
     * @memberof VectorConfig
     */
    revision?: string;
    /**
     * Optional model name for query vectorization (max 210 characters). If not specified, uses 'model' for both documents and queries.
     * @type {string}
     * @memberof VectorConfig
     */
    query_model?: string;
    /**
     * Optional model revision for query vectorization (max 210 characters). If not specified, uses 'revision' for both documents and queries.
     * @type {string}
     * @memberof VectorConfig
     */
    query_revision?: string;
    /**
     * Dimensions for the vector. Required for dense_custom vectors. For dense_model vectors, auto-detected if not specified.
     * @type {number}
     * @memberof VectorConfig
     */
    dimensions?: number;
    /**
     * Number of top-scoring terms to keep for sparse vectors. Used by sparse_model, full_text, trigrams, whitespace, wmtr, and sparse_custom vectors. Ignored by dense vectors.
     * @type {number}
     * @memberof VectorConfig
     */
    top_k?: number;
    /**
     * Percentage of WMTR top_k allocated to word weights.
     * @type {number}
     * @memberof VectorConfig
     */
    wmtr_word_weight?: number;
    /**
     * List of fields to index with this vector (name, description, content). Defaults to ['content'] if not specified.
     * @type {Array<VectorConfigIndexFieldsEnum>}
     * @memberof VectorConfig
     */
    index_fields?: Array<VectorConfigIndexFieldsEnum>;
    /**
     * Two-letter ISO 639-1 language code for language-based vector types (e.g., 'en', 'es', 'fr')
     * @type {string}
     * @memberof VectorConfig
     */
    language_default_code?: string;
    /**
     * Whether to automatically detect language for language-based vector types
     * @type {boolean}
     * @memberof VectorConfig
     */
    language_detect?: boolean;
    /**
     * Minimum confidence threshold for language detection. If detection confidence is below this value, language_default_code will be used instead.
     * @type {number}
     * @memberof VectorConfig
     */
    language_confidence?: number;
    /**
     * Whether to normalize vectors. Only supported for dense vectors. Sparse vectors do not support normalization.
     * @type {boolean}
     * @memberof VectorConfig
     */
    normalization?: boolean;
    /**
     * Distance metric for dense vectors (cosine, dot, euclid). Defaults to cosine.
     * @type {VectorConfigDenseDistanceEnum}
     * @memberof VectorConfig
     */
    dense_distance?: VectorConfigDenseDistanceEnum;
    /**
     * Whether to keep original case for text preprocessing. Only applies to model-based vectors (dense_model, sparse_model). Defaults to False (lowercase).
     * @type {boolean}
     * @memberof VectorConfig
     */
    keep_case?: boolean;
}


/**
 * @export
 */
export const VectorConfigTypeEnum = {
    DenseModel: 'dense_model',
    SparseModel: 'sparse_model',
    FullText: 'full_text',
    Trigrams: 'trigrams',
    Whitespace: 'whitespace',
    Wmtr: 'wmtr',
    Keyword: 'keyword',
    DenseCustom: 'dense_custom',
    SparseCustom: 'sparse_custom'
} as const;
export type VectorConfigTypeEnum = typeof VectorConfigTypeEnum[keyof typeof VectorConfigTypeEnum];

/**
 * @export
 */
export const VectorConfigIndexFieldsEnum = {
    Name: 'name',
    Description: 'description',
    Content: 'content'
} as const;
export type VectorConfigIndexFieldsEnum = typeof VectorConfigIndexFieldsEnum[keyof typeof VectorConfigIndexFieldsEnum];

/**
 * @export
 */
export const VectorConfigDenseDistanceEnum = {
    Cosine: 'cosine',
    Dot: 'dot',
    Euclid: 'euclid'
} as const;
export type VectorConfigDenseDistanceEnum = typeof VectorConfigDenseDistanceEnum[keyof typeof VectorConfigDenseDistanceEnum];


/**
 * Check if a given object implements the VectorConfig interface.
 */
export function instanceOfVectorConfig(value: object): value is VectorConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function VectorConfigFromJSON(json: any): VectorConfig {
    return VectorConfigFromJSONTyped(json, false);
}

export function VectorConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'model': json['model'] == null ? undefined : json['model'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'query_model': json['query_model'] == null ? undefined : json['query_model'],
        'query_revision': json['query_revision'] == null ? undefined : json['query_revision'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'top_k': json['top_k'] == null ? undefined : json['top_k'],
        'wmtr_word_weight': json['wmtr_word_weight'] == null ? undefined : json['wmtr_word_weight'],
        'index_fields': json['index_fields'] == null ? undefined : json['index_fields'],
        'language_default_code': json['language_default_code'] == null ? undefined : json['language_default_code'],
        'language_detect': json['language_detect'] == null ? undefined : json['language_detect'],
        'language_confidence': json['language_confidence'] == null ? undefined : json['language_confidence'],
        'normalization': json['normalization'] == null ? undefined : json['normalization'],
        'dense_distance': json['dense_distance'] == null ? undefined : json['dense_distance'],
        'keep_case': json['keep_case'] == null ? undefined : json['keep_case'],
    };
}

export function VectorConfigToJSON(json: any): VectorConfig {
    return VectorConfigToJSONTyped(json, false);
}

export function VectorConfigToJSONTyped(value?: VectorConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'model': value['model'],
        'revision': value['revision'],
        'query_model': value['query_model'],
        'query_revision': value['query_revision'],
        'dimensions': value['dimensions'],
        'top_k': value['top_k'],
        'wmtr_word_weight': value['wmtr_word_weight'],
        'index_fields': value['index_fields'],
        'language_default_code': value['language_default_code'],
        'language_detect': value['language_detect'],
        'language_confidence': value['language_confidence'],
        'normalization': value['normalization'],
        'dense_distance': value['dense_distance'],
        'keep_case': value['keep_case'],
    };
}

