/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Individual vector score for a search result
 * @export
 * @interface VectorScore
 */
export interface VectorScore {
    /**
     * Document field that was searched (name, description, content)
     * @type {string}
     * @memberof VectorScore
     */
    field: string;
    /**
     * Vector name that was used (wmtr, splade, dense, etc.)
     * @type {string}
     * @memberof VectorScore
     */
    vector: string;
    /**
     * Raw score from this vector
     * @type {number}
     * @memberof VectorScore
     */
    score: number;
    /**
     * Rank of this result within this vector's results (1-based)
     * @type {number}
     * @memberof VectorScore
     */
    rank: number;
}

/**
 * Check if a given object implements the VectorScore interface.
 */
export function instanceOfVectorScore(value: object): value is VectorScore {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('vector' in value) || value['vector'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    return true;
}

export function VectorScoreFromJSON(json: any): VectorScore {
    return VectorScoreFromJSONTyped(json, false);
}

export function VectorScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorScore {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'vector': json['vector'],
        'score': json['score'],
        'rank': json['rank'],
    };
}

export function VectorScoreToJSON(json: any): VectorScore {
    return VectorScoreToJSONTyped(json, false);
}

export function VectorScoreToJSONTyped(value?: VectorScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'vector': value['vector'],
        'score': value['score'],
        'rank': value['rank'],
    };
}

