/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration for a vector search option.
 * Used in search queries to specify which vectors to search with and their weights.
 * @export
 * @interface VectorSearchOption
 */
export interface VectorSearchOption {
    /**
     * Name of the vector to search with
     * @type {string}
     * @memberof VectorSearchOption
     */
    vector_name: string;
    /**
     * Weight to apply to this vector's search results
     * @type {number}
     * @memberof VectorSearchOption
     */
    weight?: number;
    /**
     * Field to search with this vector (name, description, content)
     * @type {VectorSearchOptionFieldEnum}
     * @memberof VectorSearchOption
     */
    field: VectorSearchOptionFieldEnum;
    /**
     * WMTR trigram channel multiplier for this vector option (used when vector_name is a WMTR vector).
     * @type {number}
     * @memberof VectorSearchOption
     */
    wmtr_trigram_weight?: number;
}


/**
 * @export
 */
export const VectorSearchOptionFieldEnum = {
    Name: 'name',
    Description: 'description',
    Content: 'content'
} as const;
export type VectorSearchOptionFieldEnum = typeof VectorSearchOptionFieldEnum[keyof typeof VectorSearchOptionFieldEnum];


/**
 * Check if a given object implements the VectorSearchOption interface.
 */
export function instanceOfVectorSearchOption(value: object): value is VectorSearchOption {
    if (!('vector_name' in value) || value['vector_name'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    return true;
}

export function VectorSearchOptionFromJSON(json: any): VectorSearchOption {
    return VectorSearchOptionFromJSONTyped(json, false);
}

export function VectorSearchOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorSearchOption {
    if (json == null) {
        return json;
    }
    return {
        
        'vector_name': json['vector_name'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'field': json['field'],
        'wmtr_trigram_weight': json['wmtr_trigram_weight'] == null ? undefined : json['wmtr_trigram_weight'],
    };
}

export function VectorSearchOptionToJSON(json: any): VectorSearchOption {
    return VectorSearchOptionToJSONTyped(json, false);
}

export function VectorSearchOptionToJSONTyped(value?: VectorSearchOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vector_name': value['vector_name'],
        'weight': value['weight'],
        'field': value['field'],
        'wmtr_trigram_weight': value['wmtr_trigram_weight'],
    };
}
