/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Vector data: dense (list of floats) or sparse (list of (index, value) tuples)
 * @export
 * @interface Vector
 */
export interface Vector {
}

/**
 * Check if a given object implements the Vector interface.
 */
export function instanceOfVector(value: object): value is Vector {
    return true;
}

export function VectorFromJSON(json: any): Vector {
    return VectorFromJSONTyped(json, false);
}

export function VectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vector {
    return json;
}

export function VectorToJSON(json: any): Vector {
    return VectorToJSONTyped(json, false);
}

export function VectorToJSONTyped(value?: Vector | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

