/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WindowMetrics } from './WindowMetrics';
import {
    WindowMetricsFromJSON,
    WindowMetricsFromJSONTyped,
    WindowMetricsToJSON,
    WindowMetricsToJSONTyped,
} from './WindowMetrics';

/**
 * Metrics for a single vector type (or model) on a node.
 * @export
 * @interface VectorMetrics
 */
export interface VectorMetrics {
    /**
     * Vector type (e.g. dense_model, sparse_model, wmtr, trigrams)
     * @type {string}
     * @memberof VectorMetrics
     */
    type: string;
    /**
     * Model name for transformer-based types; null for rule-based types
     * @type {string}
     * @memberof VectorMetrics
     */
    model?: string;
    /**
     * Model revision/commit hash; null if not specified or not applicable
     * @type {string}
     * @memberof VectorMetrics
     */
    revision?: string;
    /**
     * Per-window metrics keyed by window size in seconds (5, 30, 60, 300)
     * @type {{ [key: string]: WindowMetrics; }}
     * @memberof VectorMetrics
     */
    windows?: { [key: string]: WindowMetrics; };
}

/**
 * Check if a given object implements the VectorMetrics interface.
 */
export function instanceOfVectorMetrics(value: object): value is VectorMetrics {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function VectorMetricsFromJSON(json: any): VectorMetrics {
    return VectorMetricsFromJSONTyped(json, false);
}

export function VectorMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'model': json['model'] == null ? undefined : json['model'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'windows': json['windows'] == null ? undefined : (mapValues(json['windows'], WindowMetricsFromJSON)),
    };
}

export function VectorMetricsToJSON(json: any): VectorMetrics {
    return VectorMetricsToJSONTyped(json, false);
}

export function VectorMetricsToJSONTyped(value?: VectorMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'model': value['model'],
        'revision': value['revision'],
        'windows': value['windows'] == null ? undefined : (mapValues(value['windows'], WindowMetricsToJSON)),
    };
}

