/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Mergeable numerator/denominator stats for a single window.
 * @export
 * @interface WindowSample
 */
export interface WindowSample {
    /**
     * Mergeable numerator for the window
     * @type {number}
     * @memberof WindowSample
     */
    value: number;
    /**
     * Mergeable denominator for average-like metrics
     * @type {number}
     * @memberof WindowSample
     */
    n?: number;
}

/**
 * Check if a given object implements the WindowSample interface.
 */
export function instanceOfWindowSample(value: object): value is WindowSample {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function WindowSampleFromJSON(json: any): WindowSample {
    return WindowSampleFromJSONTyped(json, false);
}

export function WindowSampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WindowSample {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'n': json['n'] == null ? undefined : json['n'],
    };
}

export function WindowSampleToJSON(json: any): WindowSample {
    return WindowSampleToJSONTyped(json, false);
}

export function WindowSampleToJSONTyped(value?: WindowSample | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'n': value['n'],
    };
}

