/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Embedding throughput and latency stats for a single time window.
 * @export
 * @interface WindowMetrics
 */
export interface WindowMetrics {
    /**
     * Requests per second over this window
     * @type {number}
     * @memberof WindowMetrics
     */
    rps: number;
    /**
     * Average embedding latency in milliseconds over this window
     * @type {number}
     * @memberof WindowMetrics
     */
    avg_ms: number;
    /**
     * Number of requests observed in this window
     * @type {number}
     * @memberof WindowMetrics
     */
    n: number;
}

/**
 * Check if a given object implements the WindowMetrics interface.
 */
export function instanceOfWindowMetrics(value: object): value is WindowMetrics {
    if (!('rps' in value) || value['rps'] === undefined) return false;
    if (!('avg_ms' in value) || value['avg_ms'] === undefined) return false;
    if (!('n' in value) || value['n'] === undefined) return false;
    return true;
}

export function WindowMetricsFromJSON(json: any): WindowMetrics {
    return WindowMetricsFromJSONTyped(json, false);
}

export function WindowMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WindowMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'rps': json['rps'],
        'avg_ms': json['avg_ms'],
        'n': json['n'],
    };
}

export function WindowMetricsToJSON(json: any): WindowMetrics {
    return WindowMetricsToJSONTyped(json, false);
}

export function WindowMetricsToJSONTyped(value?: WindowMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rps': value['rps'],
        'avg_ms': value['avg_ms'],
        'n': value['n'],
    };
}

