/* tslint:disable */
/* eslint-disable */
/**
 * Amalgam Index API
 * Amalgam Index (Amgix). Open-Source Hybrid Search System
 *
 * The version of the OpenAPI document: 1.2.0-dash
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkUploadRequest,
  CollectionConfig,
  CollectionExistsResponse,
  CollectionStatsResponse,
  Document,
  DocumentStatusResponse,
  HTTPValidationError,
  MetricDefinitionItem,
  MetricTrend,
  Metrics,
  OkResponse,
  QueueInfo,
  ReadyResponse,
  SearchQuery,
  SearchResult,
  SystemInfoResponse,
  VersionResponse,
} from '../models/index';
import {
    BulkUploadRequestFromJSON,
    BulkUploadRequestToJSON,
    CollectionConfigFromJSON,
    CollectionConfigToJSON,
    CollectionExistsResponseFromJSON,
    CollectionExistsResponseToJSON,
    CollectionStatsResponseFromJSON,
    CollectionStatsResponseToJSON,
    DocumentFromJSON,
    DocumentToJSON,
    DocumentStatusResponseFromJSON,
    DocumentStatusResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MetricDefinitionItemFromJSON,
    MetricDefinitionItemToJSON,
    MetricTrendFromJSON,
    MetricTrendToJSON,
    MetricsFromJSON,
    MetricsToJSON,
    OkResponseFromJSON,
    OkResponseToJSON,
    QueueInfoFromJSON,
    QueueInfoToJSON,
    ReadyResponseFromJSON,
    ReadyResponseToJSON,
    SearchQueryFromJSON,
    SearchQueryToJSON,
    SearchResultFromJSON,
    SearchResultToJSON,
    SystemInfoResponseFromJSON,
    SystemInfoResponseToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from '../models/index';

export interface CollectionExistsRequest {
    collectionName: string;
}

export interface CreateCollectionRequest {
    collectionName: string;
    collectionConfig: CollectionConfig;
}

export interface DeleteCollectionRequest {
    collectionName: string;
}

export interface DeleteCollectionQueueRequest {
    collectionName: string;
}

export interface DeleteDocumentRequest {
    collectionName: string;
    documentId: string;
}

export interface EmptyCollectionRequest {
    collectionName: string;
}

export interface GetCollectionConfigRequest {
    collectionName: string;
}

export interface GetCollectionQueueInfoRequest {
    collectionName: string;
}

export interface GetCollectionStatsRequest {
    collectionName: string;
}

export interface GetDocumentRequest {
    collectionName: string;
    documentId: string;
}

export interface GetDocumentStatusRequest {
    collectionName: string;
    documentId: string;
}

export interface MetricsCurrentRequest {
    window?: number;
    keys?: Array<string>;
}

export interface MetricsTrendsRequest {
    since: Date;
    until: Date;
    resolution?: number;
    keys?: Array<string>;
}

export interface SearchRequest {
    collectionName: string;
    searchQuery: SearchQuery;
}

export interface UpsertDocumentRequest {
    collectionName: string;
    document: Document;
}

export interface UpsertDocumentSyncRequest {
    collectionName: string;
    document: Document;
}

export interface UpsertDocumentsBulkRequest {
    collectionName: string;
    bulkUploadRequest: BulkUploadRequest;
}

/**
 * 
 */
export class AmgixApi extends runtime.BaseAPI {

    /**
     * Creates request options for collectionExists without sending the request
     */
    async collectionExistsRequestOpts(requestParameters: CollectionExistsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling collectionExists().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/exists`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check if a collection exists. Always returns 200 with exists true or false.
     * Collection Exists
     */
    async collectionExistsRaw(requestParameters: CollectionExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionExistsResponse>> {
        const requestOptions = await this.collectionExistsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionExistsResponseFromJSON(jsonValue));
    }

    /**
     * Check if a collection exists. Always returns 200 with exists true or false.
     * Collection Exists
     */
    async collectionExists(requestParameters: CollectionExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionExistsResponse> {
        const response = await this.collectionExistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCollection without sending the request
     */
    async createCollectionRequestOpts(requestParameters: CreateCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling createCollection().'
            );
        }

        if (requestParameters['collectionConfig'] == null) {
            throw new runtime.RequiredError(
                'collectionConfig',
                'Required parameter "collectionConfig" was null or undefined when calling createCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/collections/{collection_name}`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionConfigToJSON(requestParameters['collectionConfig']),
        };
    }

    /**
     * Create a new collection.  This endpoint creates a new collection with the specified name and vector configurations. It validates the provided model configurations and ensures all required features are supported by the database.  Args:     collection_name: The unique name for the new collection (alphanumeric, underscores, hyphens only).     config: Configuration details for the collection, including vector types and storage options.  Returns:     An `OkResponse` object indicating the success of the operation.  Raises:     HTTPException:         - 400 if model validation fails or required features are not supported.         - 409 if a collection with the same name already exists.         - 500 if the collection creation fails in the database.
     * Create Collection
     */
    async createCollectionRaw(requestParameters: CreateCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.createCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Create a new collection.  This endpoint creates a new collection with the specified name and vector configurations. It validates the provided model configurations and ensures all required features are supported by the database.  Args:     collection_name: The unique name for the new collection (alphanumeric, underscores, hyphens only).     config: Configuration details for the collection, including vector types and storage options.  Returns:     An `OkResponse` object indicating the success of the operation.  Raises:     HTTPException:         - 400 if model validation fails or required features are not supported.         - 409 if a collection with the same name already exists.         - 500 if the collection creation fails in the database.
     * Create Collection
     */
    async createCollection(requestParameters: CreateCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.createCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCollection without sending the request
     */
    async deleteCollectionRequestOpts(requestParameters: DeleteCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling deleteCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a collection.  Deletes a collection and all its associated data. This operation is irreversible.  Args:     collection_name: The name of the collection to delete.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Delete Collection
     */
    async deleteCollectionRaw(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.deleteCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Delete a collection.  Deletes a collection and all its associated data. This operation is irreversible.  Args:     collection_name: The name of the collection to delete.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Delete Collection
     */
    async deleteCollection(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.deleteCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCollectionQueue without sending the request
     */
    async deleteCollectionQueueRequestOpts(requestParameters: DeleteCollectionQueueRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling deleteCollectionQueue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/queue`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete all queue entries for a collection.  Removes all documents from the processing queue for a specified collection. This does not affect documents already indexed in the collection.  Args:     collection_name: The name of the collection for which to delete queue entries.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Delete Collection Queue
     */
    async deleteCollectionQueueRaw(requestParameters: DeleteCollectionQueueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.deleteCollectionQueueRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Delete all queue entries for a collection.  Removes all documents from the processing queue for a specified collection. This does not affect documents already indexed in the collection.  Args:     collection_name: The name of the collection for which to delete queue entries.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Delete Collection Queue
     */
    async deleteCollectionQueue(requestParameters: DeleteCollectionQueueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.deleteCollectionQueueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDocument without sending the request
     */
    async deleteDocumentRequestOpts(requestParameters: DeleteDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling deleteDocument().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling deleteDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/documents/{document_id}`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a document.  Deletes a specific document by its ID from the specified collection.  Args:     collection_name: The name of the collection.     document_id: The unique identifier of the document to delete.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Delete Document
     */
    async deleteDocumentRaw(requestParameters: DeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.deleteDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Delete a document.  Deletes a specific document by its ID from the specified collection.  Args:     collection_name: The name of the collection.     document_id: The unique identifier of the document to delete.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Delete Document
     */
    async deleteDocument(requestParameters: DeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.deleteDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for emptyCollection without sending the request
     */
    async emptyCollectionRequestOpts(requestParameters: EmptyCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling emptyCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/empty`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Empty a collection.  Removes all documents and their associated vector data from a specified collection, but keeps the collection\'s configuration.  Args:     collection_name: The name of the collection to empty.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Empty Collection
     */
    async emptyCollectionRaw(requestParameters: EmptyCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.emptyCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Empty a collection.  Removes all documents and their associated vector data from a specified collection, but keeps the collection\'s configuration.  Args:     collection_name: The name of the collection to empty.  Returns:     An `OkResponse` object indicating the success of the operation.
     * Empty Collection
     */
    async emptyCollection(requestParameters: EmptyCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.emptyCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollectionConfig without sending the request
     */
    async getCollectionConfigRequestOpts(requestParameters: GetCollectionConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getCollectionConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get collection configuration.  Retrieves the configuration details for a specific collection.  Args:     collection_name: The name of the collection.  Returns:     The configuration of the specified collection.
     * Get Collection Config
     */
    async getCollectionConfigRaw(requestParameters: GetCollectionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionConfig>> {
        const requestOptions = await this.getCollectionConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionConfigFromJSON(jsonValue));
    }

    /**
     * Get collection configuration.  Retrieves the configuration details for a specific collection.  Args:     collection_name: The name of the collection.  Returns:     The configuration of the specified collection.
     * Get Collection Config
     */
    async getCollectionConfig(requestParameters: GetCollectionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionConfig> {
        const response = await this.getCollectionConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollectionQueueInfo without sending the request
     */
    async getCollectionQueueInfoRequestOpts(requestParameters: GetCollectionQueueInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getCollectionQueueInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/queue/info`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get queue statistics for a collection.  Retrieves counts of documents in different queue states (queued, requeued, failed).  Args:     collection_name: The name of the collection.  Returns:     A `QueueInfo` object with counts for each queue state.
     * Get Collection Queue Info
     */
    async getCollectionQueueInfoRaw(requestParameters: GetCollectionQueueInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueInfo>> {
        const requestOptions = await this.getCollectionQueueInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueInfoFromJSON(jsonValue));
    }

    /**
     * Get queue statistics for a collection.  Retrieves counts of documents in different queue states (queued, requeued, failed).  Args:     collection_name: The name of the collection.  Returns:     A `QueueInfo` object with counts for each queue state.
     * Get Collection Queue Info
     */
    async getCollectionQueueInfo(requestParameters: GetCollectionQueueInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueInfo> {
        const response = await this.getCollectionQueueInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollectionStats without sending the request
     */
    async getCollectionStatsRequestOpts(requestParameters: GetCollectionStatsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getCollectionStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/stats`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get persisted collection statistics and queue counts.  Returns document counts maintained by the indexing pipeline (not a live physical count), plus queue entry counts by state (same data as ``GET .../queue/info``).  Args:     collection_name: The name of the collection.  Returns:     A `CollectionStatsResponse` with `doc_count` and `queue`.  Raises:     HTTPException: 404 if the collection does not exist.
     * Get Collection Stats
     */
    async getCollectionStatsRaw(requestParameters: GetCollectionStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionStatsResponse>> {
        const requestOptions = await this.getCollectionStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionStatsResponseFromJSON(jsonValue));
    }

    /**
     * Get persisted collection statistics and queue counts.  Returns document counts maintained by the indexing pipeline (not a live physical count), plus queue entry counts by state (same data as ``GET .../queue/info``).  Args:     collection_name: The name of the collection.  Returns:     A `CollectionStatsResponse` with `doc_count` and `queue`.  Raises:     HTTPException: 404 if the collection does not exist.
     * Get Collection Stats
     */
    async getCollectionStats(requestParameters: GetCollectionStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionStatsResponse> {
        const response = await this.getCollectionStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDocument without sending the request
     */
    async getDocumentRequestOpts(requestParameters: GetDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getDocument().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/documents/{document_id}`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a single document.  Retrieves a specific document by its ID from the specified collection.  Args:     collection_name: The name of the collection.     document_id: The unique identifier of the document to retrieve.  Returns:     The retrieved `Document` object.  Raises:     HTTPException: 404 if the document is not found in the collection.
     * Get Document
     */
    async getDocumentRaw(requestParameters: GetDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Document>> {
        const requestOptions = await this.getDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentFromJSON(jsonValue));
    }

    /**
     * Retrieve a single document.  Retrieves a specific document by its ID from the specified collection.  Args:     collection_name: The name of the collection.     document_id: The unique identifier of the document to retrieve.  Returns:     The retrieved `Document` object.  Raises:     HTTPException: 404 if the document is not found in the collection.
     * Get Document
     */
    async getDocument(requestParameters: GetDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Document> {
        const response = await this.getDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDocumentStatus without sending the request
     */
    async getDocumentStatusRequestOpts(requestParameters: GetDocumentStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getDocumentStatus().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getDocumentStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections/{collection_name}/documents/{document_id}/status`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));
        urlPath = urlPath.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get document processing status.  Retrieves the processing status of a document, including its current state in the queue and any associated messages.  Args:     collection_name: The name of the collection.     document_id: The unique identifier of the document.  Returns:     A `DocumentStatusResponse` object containing the processing status of the document.  Raises:     HTTPException: 404 if the document is not found in the collection\'s queue.
     * Get Document Status
     */
    async getDocumentStatusRaw(requestParameters: GetDocumentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentStatusResponse>> {
        const requestOptions = await this.getDocumentStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get document processing status.  Retrieves the processing status of a document, including its current state in the queue and any associated messages.  Args:     collection_name: The name of the collection.     document_id: The unique identifier of the document.  Returns:     A `DocumentStatusResponse` object containing the processing status of the document.  Raises:     HTTPException: 404 if the document is not found in the collection\'s queue.
     * Get Document Status
     */
    async getDocumentStatus(requestParameters: GetDocumentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentStatusResponse> {
        const response = await this.getDocumentStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthCheck without sending the request
     */
    async healthCheckRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/health/check`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check API service responsiveness.  This endpoint returns a simple \'ok\' status to indicate that the API service is running and able to respond to requests.  Returns:     An `OkResponse` object with the \'ok\' field set to True, confirming the service\'s responsiveness.
     * Health
     */
    async healthCheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.healthCheckRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Check API service responsiveness.  This endpoint returns a simple \'ok\' status to indicate that the API service is running and able to respond to requests.  Returns:     An `OkResponse` object with the \'ok\' field set to True, confirming the service\'s responsiveness.
     * Health
     */
    async healthCheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.healthCheckRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthReady without sending the request
     */
    async healthReadyRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/health/ready`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check if service is ready to handle requests.  Runs four probes: database, rabbitmq, encoder (ping-encoder), rpc (ping-rpc). Returns 200 if all pass (fully ready), 218 if some fail (partial ready). Response body always includes all four probe results and a ready flag.
     * Readiness Check
     */
    async healthReadyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadyResponse>> {
        const requestOptions = await this.healthReadyRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadyResponseFromJSON(jsonValue));
    }

    /**
     * Check if service is ready to handle requests.  Runs four probes: database, rabbitmq, encoder (ping-encoder), rpc (ping-rpc). Returns 200 if all pass (fully ready), 218 if some fail (partial ready). Response body always includes all four probe results and a ready flag.
     * Readiness Check
     */
    async healthReady(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadyResponse> {
        const response = await this.healthReadyRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCollections without sending the request
     */
    async listCollectionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/collections`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all available collections.  Retrieves a list of all collections managed by the application.  Returns:     A list of strings, where each string is the name of an available collection.
     * List Collections
     */
    async listCollectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.listCollectionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List all available collections.  Retrieves a list of all collections managed by the application.  Returns:     A list of strings, where each string is the name of an available collection.
     * List Collections
     */
    async listCollections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listCollectionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for metricsCurrent without sending the request
     */
    async metricsCurrentRequestOpts(requestParameters: MetricsCurrentRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['window'] != null) {
            queryParameters['window'] = requestParameters['window'];
        }

        if (requestParameters['keys'] != null) {
            queryParameters['keys'] = requestParameters['keys'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/metrics/current`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the current metrics state for all nodes over the given window (seconds).
     * Metrics Current
     */
    async metricsCurrentRaw(requestParameters: MetricsCurrentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metrics>> {
        const requestOptions = await this.metricsCurrentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricsFromJSON(jsonValue));
    }

    /**
     * Return the current metrics state for all nodes over the given window (seconds).
     * Metrics Current
     */
    async metricsCurrent(requestParameters: MetricsCurrentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metrics> {
        const response = await this.metricsCurrentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for metricsDefinitions without sending the request
     */
    async metricsDefinitionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/metrics/definitions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return catalog entries for all known metric keys, their units, and descriptions.
     * Metrics Definitions
     */
    async metricsDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetricDefinitionItem>>> {
        const requestOptions = await this.metricsDefinitionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetricDefinitionItemFromJSON));
    }

    /**
     * Return catalog entries for all known metric keys, their units, and descriptions.
     * Metrics Definitions
     */
    async metricsDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetricDefinitionItem>> {
        const response = await this.metricsDefinitionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for metricsTrends without sending the request
     */
    async metricsTrendsRequestOpts(requestParameters: MetricsTrendsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['since'] == null) {
            throw new runtime.RequiredError(
                'since',
                'Required parameter "since" was null or undefined when calling metricsTrends().'
            );
        }

        if (requestParameters['until'] == null) {
            throw new runtime.RequiredError(
                'until',
                'Required parameter "until" was null or undefined when calling metricsTrends().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['since'] != null) {
            queryParameters['since'] = (requestParameters['since'] as any).toISOString();
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = (requestParameters['until'] as any).toISOString();
        }

        if (requestParameters['resolution'] != null) {
            queryParameters['resolution'] = requestParameters['resolution'];
        }

        if (requestParameters['keys'] != null) {
            queryParameters['keys'] = requestParameters['keys'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/metrics/trends`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return historical metric buckets for the given time range and resolution.  Args:     since: Inclusive start of the time range (ISO 8601, UTC assumed if no timezone given).     until: Exclusive end of the time range (ISO 8601, UTC assumed if no timezone given).     resolution: Bucket size in seconds — 60 for 1-minute, 300 for 5-minute.     keys: One or more metric keys to return. Omit to return all keys.
     * Metrics Trends
     */
    async metricsTrendsRaw(requestParameters: MetricsTrendsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MetricTrend>>> {
        const requestOptions = await this.metricsTrendsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetricTrendFromJSON));
    }

    /**
     * Return historical metric buckets for the given time range and resolution.  Args:     since: Inclusive start of the time range (ISO 8601, UTC assumed if no timezone given).     until: Exclusive end of the time range (ISO 8601, UTC assumed if no timezone given).     resolution: Bucket size in seconds — 60 for 1-minute, 300 for 5-minute.     keys: One or more metric keys to return. Omit to return all keys.
     * Metrics Trends
     */
    async metricsTrends(requestParameters: MetricsTrendsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MetricTrend>> {
        const response = await this.metricsTrendsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for search without sending the request
     */
    async searchRequestOpts(requestParameters: SearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling search().'
            );
        }

        if (requestParameters['searchQuery'] == null) {
            throw new runtime.RequiredError(
                'searchQuery',
                'Required parameter "searchQuery" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/collections/{collection_name}/search`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchQueryToJSON(requestParameters['searchQuery']),
        };
    }

    /**
     * Perform a search query on a collection.  Executes a search query against the specified collection.  Args:     collection_name: The name of the collection to search.     query: The `SearchQuery` object containing the search text, filters, and other parameters.  Returns:     A list of `SearchResult` objects, where each object represents a search result.
     * Search
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResult>>> {
        const requestOptions = await this.searchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultFromJSON));
    }

    /**
     * Perform a search query on a collection.  Executes a search query against the specified collection.  Args:     collection_name: The name of the collection to search.     query: The `SearchQuery` object containing the search text, filters, and other parameters.  Returns:     A list of `SearchResult` objects, where each object represents a search result.
     * Search
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResult>> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for systemInfo without sending the request
     */
    async systemInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/system/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Summarize deployment and infrastructure (no connection URLs).
     * System Info
     */
    async systemInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemInfoResponse>> {
        const requestOptions = await this.systemInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemInfoResponseFromJSON(jsonValue));
    }

    /**
     * Summarize deployment and infrastructure (no connection URLs).
     * System Info
     */
    async systemInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemInfoResponse> {
        const response = await this.systemInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertDocument without sending the request
     */
    async upsertDocumentRequestOpts(requestParameters: UpsertDocumentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling upsertDocument().'
            );
        }

        if (requestParameters['document'] == null) {
            throw new runtime.RequiredError(
                'document',
                'Required parameter "document" was null or undefined when calling upsertDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/collections/{collection_name}/documents`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentToJSON(requestParameters['document']),
        };
    }

    /**
     * Upsert a single document asynchronously.  Adds or updates a single document in the specified collection by placing it into a processing queue. The document will be vectorized and indexed asynchronously.  Args:     collection_name: The name of the collection to upsert the document into.     document: The document object to be upserted.  Returns:     An `OkResponse` object indicating that the document has been accepted for processing.  Raises:     HTTPException: 500 if publishing the event to the internal queue fails.
     * Upsert Document
     */
    async upsertDocumentRaw(requestParameters: UpsertDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.upsertDocumentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Upsert a single document asynchronously.  Adds or updates a single document in the specified collection by placing it into a processing queue. The document will be vectorized and indexed asynchronously.  Args:     collection_name: The name of the collection to upsert the document into.     document: The document object to be upserted.  Returns:     An `OkResponse` object indicating that the document has been accepted for processing.  Raises:     HTTPException: 500 if publishing the event to the internal queue fails.
     * Upsert Document
     */
    async upsertDocument(requestParameters: UpsertDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.upsertDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertDocumentSync without sending the request
     */
    async upsertDocumentSyncRequestOpts(requestParameters: UpsertDocumentSyncRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling upsertDocumentSync().'
            );
        }

        if (requestParameters['document'] == null) {
            throw new runtime.RequiredError(
                'document',
                'Required parameter "document" was null or undefined when calling upsertDocumentSync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/collections/{collection_name}/documents/sync`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentToJSON(requestParameters['document']),
        };
    }

    /**
     * Upsert a single document synchronously.  Adds or updates a single document in the specified collection and waits for the operation to complete, including vectorization and indexing.  Args:     collection_name: The name of the collection to upsert the document into.     document: The document object to be upserted.  Returns:     An `OkResponse` object indicating the success of the operation.  Raises:     HTTPException:         - 409 if a document with the same ID and newer timestamp already exists (conflict).         - 500 for other internal server errors during processing.
     * Upsert Document Sync
     */
    async upsertDocumentSyncRaw(requestParameters: UpsertDocumentSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.upsertDocumentSyncRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Upsert a single document synchronously.  Adds or updates a single document in the specified collection and waits for the operation to complete, including vectorization and indexing.  Args:     collection_name: The name of the collection to upsert the document into.     document: The document object to be upserted.  Returns:     An `OkResponse` object indicating the success of the operation.  Raises:     HTTPException:         - 409 if a document with the same ID and newer timestamp already exists (conflict).         - 500 for other internal server errors during processing.
     * Upsert Document Sync
     */
    async upsertDocumentSync(requestParameters: UpsertDocumentSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.upsertDocumentSyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertDocumentsBulk without sending the request
     */
    async upsertDocumentsBulkRequestOpts(requestParameters: UpsertDocumentsBulkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling upsertDocumentsBulk().'
            );
        }

        if (requestParameters['bulkUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkUploadRequest',
                'Required parameter "bulkUploadRequest" was null or undefined when calling upsertDocumentsBulk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/collections/{collection_name}/documents/bulk`;
        urlPath = urlPath.replace(`{${"collection_name"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkUploadRequestToJSON(requestParameters['bulkUploadRequest']),
        };
    }

    /**
     * Upsert multiple documents in bulk asynchronously.  Adds or updates multiple documents in the specified collection by placing them into a processing queue. Documents will be vectorized and indexed asynchronously. This method is optimized for bulk operations.  Args:     collection_name: The name of the collection to upsert the documents into.     request: A `BulkUploadRequest` object containing a list of `Document` objects to be upserted.  Returns:     An `OkResponse` object indicating that the documents have been accepted for processing.  Raises:     HTTPException: 500 if publishing events to the internal queue fails for any document.
     * Upsert Documents Bulk
     */
    async upsertDocumentsBulkRaw(requestParameters: UpsertDocumentsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkResponse>> {
        const requestOptions = await this.upsertDocumentsBulkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkResponseFromJSON(jsonValue));
    }

    /**
     * Upsert multiple documents in bulk asynchronously.  Adds or updates multiple documents in the specified collection by placing them into a processing queue. Documents will be vectorized and indexed asynchronously. This method is optimized for bulk operations.  Args:     collection_name: The name of the collection to upsert the documents into.     request: A `BulkUploadRequest` object containing a list of `Document` objects to be upserted.  Returns:     An `OkResponse` object indicating that the documents have been accepted for processing.  Raises:     HTTPException: 500 if publishing events to the internal queue fails for any document.
     * Upsert Documents Bulk
     */
    async upsertDocumentsBulk(requestParameters: UpsertDocumentsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkResponse> {
        const response = await this.upsertDocumentsBulkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for version without sending the request
     */
    async versionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/version`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the system version.  Returns:     A `VersionResponse` object with the system version.
     * Version
     */
    async versionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionResponse>> {
        const requestOptions = await this.versionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionResponseFromJSON(jsonValue));
    }

    /**
     * Return the system version.  Returns:     A `VersionResponse` object with the system version.
     * Version
     */
    async version(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionResponse> {
        const response = await this.versionRaw(initOverrides);
        return await response.value();
    }

}
